# Generated by Django 5.2.6 on 2025-11-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_alter_coupon_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPincode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=6, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('delivery_days', models.IntegerField(default=5, help_text='Expected delivery days')),
                ('is_cod_available', models.BooleanField(default=True)),
                ('is_serviceable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Delivery Pincode',
                'verbose_name_plural': 'Delivery Pincodes',
            },
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['display_order', '-discount']},
        ),
        migrations.AddField(
            model_name='coupon',
            name='badge',
            field=models.CharField(blank=True, help_text="e.g., 'Most Popular', 'Best Value'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Lower number = higher priority'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_items',
            field=models.IntegerField(default=0, help_text='Minimum items required (0 = no minimum)'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='used_count',
            field=models.IntegerField(default=0, help_text='Number of times used'),
        ),
    ]
