# Generated by Django 5.2.6 on 2025-11-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_deliverypincode_alter_coupon_options_coupon_badge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_purchase',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
