# Generated by Django 5.2.6 on 2025-12-10 10:40

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0005_couponusage'),
        ('orders', '0014_orderitem_variant_id_alter_refund_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='couponusage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='coupon',
            name='exclude_discounted',
            field=models.BooleanField(default=False, help_text='Exclude already discounted products'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='first_time_only',
            field=models.BooleanField(default=False, help_text='Only for first-time buyers'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='per_user_limit',
            field=models.PositiveIntegerField(default=1, help_text='How many times each user can use'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date when coupon becomes active'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expiry_date',
            field=models.DateField(help_text='Date when coupon expires'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='limit',
            field=models.PositiveIntegerField(default=1, help_text='Total usage limit (all users)'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_purchase',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum cart value (0 = no limit)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_redeemable',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Max discount amount (for % coupons)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='min_purchase',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum cart value', max_digits=10),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='used_count',
            field=models.IntegerField(default=0, help_text='Number of times used globally'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['user', 'coupon'], name='coupons_cou_user_id_8b620f_idx'),
        ),
    ]
