# Generated by Django 5.2.6 on 2025-12-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0006_alter_couponusage_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypincode',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='deliverypincode',
            name='city',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='deliverypincode',
            name='pincode',
            field=models.CharField(db_index=True, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='deliverypincode',
            name='state',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='deliverypincode',
            index=models.Index(fields=['pincode', 'is_serviceable'], name='coupons_del_pincode_ae98f7_idx'),
        ),
    ]
