# Generated by Django 5.2.6 on 2025-10-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='max_redeemable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='offer_type',
            field=models.CharField(blank=True, choices=[('PERCENT', 'Percent'), ('FLAT', 'Flat')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='offer_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
