# Generated by Django 5.2.6 on 2025-10-26 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_max_redeemable_category_offer_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='max_redeemable',
        ),
        migrations.RemoveField(
            model_name='category',
            name='offer_type',
        ),
        migrations.RemoveField(
            model_name='category',
            name='offer_value',
        ),
        migrations.CreateModel(
            name='CategoryOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.PositiveIntegerField(blank=True, null=True)),
                ('discount_rupees', models.PositiveIntegerField(blank=True, null=True)),
                ('max_redeemable_price', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='category.category')),
            ],
        ),
    ]
