# Generated by Django 5.2.6 on 2025-10-26 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_remove_category_max_redeemable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryoffer',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='categoryoffer',
            name='discount_rupees',
        ),
        migrations.RemoveField(
            model_name='categoryoffer',
            name='max_redeemable_price',
        ),
        migrations.AddField(
            model_name='categoryoffer',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoryoffer',
            name='max_redeemable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='categoryoffer',
            name='offer_type',
            field=models.CharField(choices=[('percent', 'Percent'), ('rs', 'Rupees')], default=10, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoryoffer',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='category.category'),
        ),
    ]
