# Generated by Django 5.2.6 on 2025-10-28 07:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_remove_categoryoffer_discount_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryoffer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='categoryoffer',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='categoryoffer',
            name='max_redeemable',
        ),
        migrations.RemoveField(
            model_name='categoryoffer',
            name='offer_type',
        ),
        migrations.AddField(
            model_name='categoryoffer',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='categoryoffer',
            name='discount_rs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='categoryoffer',
            name='end_date',
            field=models.DateField(default='2025-10-28'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoryoffer',
            name='is_extra',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='categoryoffer',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoryoffer',
            name='title',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
