# Generated by Django 5.2.6 on 2025-11-17 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('purchase_reward', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('monthly_cap', models.PositiveIntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_used', models.CharField(db_index=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('reward_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('signed_up', 'Signed up'), ('qualified', 'Qualified'), ('rejected', 'Rejected')], db_index=True, default='signed_up', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('referee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_from', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, max_length=16, unique=True)),
                ('total_referrals', models.PositiveIntegerField(default=0)),
                ('lifetime_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
