# Generated by Django 5.2.6 on 2025-11-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_walletaccount_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralconfig',
            name='signup_reward',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
