# Generated by Django 5.2.6 on 2025-12-02 11:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_referralconfig_signup_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='walletaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('failed', 'Failed')], default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='transaction_id',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['-created_at'], name='wallet_wall_created_d9a3be_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['kind', 'status'], name='wallet_wall_kind_b2ac2f_idx'),
        ),
    ]
