# Generated by Django 5.2.6 on 2025-12-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_walletaccount_created_at_walletaccount_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_id',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
    ]
