# Generated by Django 5.2.6 on 2025-12-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_alter_wallettransaction_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='idem_key',
            field=models.CharField(blank=True, db_index=True, help_text='Idempotency key to prevent duplicate transactions', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['account', 'idem_key'], name='wallet_wall_account_796141_idx'),
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('idem_key__isnull', False)), fields=('account', 'idem_key'), name='unique_account_idem_key'),
        ),
    ]
