# Generated by Django 5.2.6 on 2025-10-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_buy_now',
            field=models.BooleanField(default=False),
        ),
    ]
