# Generated by Django 5.2.6 on 2025-10-26 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_is_buy_now'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='is_buy_now',
        ),
    ]
