# Generated by Django 5.2.6 on 2025-10-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_avatar_profile_pending_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pending_email_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
