# Generated by Django 5.2.6 on 2025-10-16 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='mrp_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_color',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
