# Generated by Django 5.2.6 on 2025-10-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_mrp_price_orderitem_variant_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='offer_label',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
