# Generated by Django 5.2.6 on 2025-12-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderitem_delivered_at_orderitem_out_for_delivery_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_days',
            field=models.IntegerField(default=5, help_text='Expected delivery days from order date'),
        ),
        migrations.AddField(
            model_name='order',
            name='expected_delivery_date',
            field=models.DateField(blank=True, help_text='Calculated expected delivery date', null=True),
        ),
    ]
