# Generated by Django 5.2.6 on 2025-12-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_delivery_days_order_expected_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delay_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_days',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
