# Generated by Django 5.2.6 on 2025-12-01 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_delay_notified_alter_order_delivery_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_type', models.CharField(choices=[('ITEM', 'Item Refund'), ('SHIPPING', 'Shipping Refund'), ('DISCOUNT', 'Discount Adjustment')], default='ITEM', max_length=20)),
                ('original_amount', models.DecimalField(decimal_places=2, help_text='Original item/line total', max_digits=12)),
                ('refund_amount', models.DecimalField(decimal_places=2, help_text='Actual refund amount (after proportional calculation)', max_digits=12)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('Completed', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('wallet_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='orders.order')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='orders.orderitem')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'status'], name='orders_refu_order_i_4763e9_idx'), models.Index(fields=['order_item'], name='orders_refu_order_i_e59703_idx')],
            },
        ),
    ]
