# Generated by Django 5.2.6 on 2025-12-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cancellation_note',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('ORDER_BY_MISTAKE', 'Ordered by mistake'), ('FOUND_CHEAPER', 'Found cheaper elsewhere'), ('DELIVERY_TOO_LATE', 'Delivery taking too long'), ('CHANGED_MIND', 'Changed my mind'), ('ORDERED_WRONG_ITEM', 'Ordered wrong item'), ('DUPLICATE_ORDER', 'Duplicate order'), ('OTHER', 'Other reason')], max_length=50, null=True),
        ),
    ]
