# Generated by Django 5.2.6 on 2025-12-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_razorpay_order_id_order_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount refunded for this item', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='refund_id',
            field=models.CharField(blank=True, help_text='Razorpay refund ID (if applicable)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='refund_method',
            field=models.CharField(blank=True, help_text='Refund method: razorpay, wallet, store_credit', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='refund_processed_at',
            field=models.DateTimeField(blank=True, help_text='When refund was completed', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='refund_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], help_text='Refund processing status', max_length=20, null=True),
        ),
    ]
