# Generated by Django 5.2.6 on 2025-12-08 11:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='featured_products/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('link_url', models.URLField(help_text='Product detail page URL', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['priority', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='dealofmonth',
            options={'ordering': ['priority', '-created_at'], 'verbose_name': 'Deal of the Month', 'verbose_name_plural': 'Deals of the Month'},
        ),
        migrations.RenameField(
            model_name='dealofmonth',
            old_name='subtitle',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='dealofmonth',
            name='left_image',
        ),
        migrations.RemoveField(
            model_name='dealofmonth',
            name='right_image',
        ),
        migrations.AddField(
            model_name='banner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='link_url',
            field=models.URLField(blank=True, help_text='Where to redirect on click', max_length=300),
        ),
        migrations.AddField(
            model_name='banner',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='banner',
            name='priority',
            field=models.PositiveIntegerField(default=1, help_text='Lower number = higher priority'),
        ),
        migrations.AddField(
            model_name='banner',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='banners/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg'])]),
        ),
        migrations.AddField(
            model_name='dealofmonth',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/images/'),
        ),
        migrations.AlterField(
            model_name='dealofmonth',
            name='ends_on',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='dealofmonth',
            name='starts_on',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='DealImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='deals/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='banner.dealofmonth')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
