# Generated by Django 5.2.6 on 2025-12-09 06:24

import banner.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_featuredproduct_alter_banner_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/images/', validators=[banner.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='banner',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='banners/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg']), banner.models.validate_video_size]),
        ),
    ]
