# Generated by Django 5.2.6 on 2025-12-09 07:36

import banner.models
import banner.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0003_alter_banner_image_alter_banner_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='video',
            field=models.FileField(blank=True, null=True, storage=banner.storage.VideoCloudinaryStorage(), upload_to='banners/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg']), banner.models.validate_video_size]),
        ),
    ]
