# Generated by Django 5.2.6 on 2025-09-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_colors',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
