# Generated by Django 5.2.6 on 2025-09-25 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_available_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_colors',
        ),
    ]
