# Generated by Django 5.2.6 on 2025-09-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_available_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_detailed',
            field=models.BooleanField(default=False),
        ),
    ]
