# Generated by Django 5.2.6 on 2025-09-26 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productimage_is_detailed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='is_detailed',
        ),
        migrations.CreateModel(
            name='ProductDetailedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/detailed/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_images', to='products.product')),
            ],
        ),
    ]
