# Generated by Django 5.2.6 on 2025-09-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_productimage_is_detailed_productdetailedimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariantimage',
            name='variant',
        ),
        migrations.AddField(
            model_name='productvariantimage',
            name='variants',
            field=models.ManyToManyField(related_name='images', to='products.productvariant'),
        ),
    ]
