# Generated by Django 5.2.6 on 2025-09-26 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_productvariantimage_variant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariantimage',
            name='variants',
        ),
        migrations.AddField(
            model_name='productvariantimage',
            name='variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productvariant'),
            preserve_default=False,
        ),
    ]
