# Generated by Django 5.2.6 on 2025-10-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_temporaryupload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-featured', 'id']},
        ),
        migrations.AlterModelOptions(
            name='productvariantimage',
            options={'ordering': ['-featured', 'id']},
        ),
        migrations.AddField(
            model_name='productimage',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariantimage',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
