# Generated by Django 5.2.6 on 2025-10-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoffer',
            name='is_extra',
            field=models.BooleanField(default=False),
        ),
    ]
