# Generated by Django 5.2.6 on 2025-10-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_productoffer_is_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoffer',
            name='is_extra',
            field=models.BooleanField(default=True),
        ),
    ]
