# Generated by Django 5.2.6 on 2025-10-30 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
