# Generated by Django 5.2.6 on 2025-12-02 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_orderitem_cancellation_note_and_more'),
        ('products', '0016_delete_wishlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, help_text='Alert when stock falls below this number'),
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('RESERVE', 'Stock Reserved (Order Placed)'), ('RELEASE', 'Stock Released (Order Cancelled/Returned)'), ('MANUAL_ADD', 'Manual Stock Addition'), ('MANUAL_SUBTRACT', 'Manual Stock Subtraction'), ('RESTOCK', 'Restocked by Admin')], max_length=20)),
                ('quantity', models.IntegerField(help_text='Change in quantity (negative for reduction, positive for addition)')),
                ('stock_before', models.PositiveIntegerField()),
                ('stock_after', models.PositiveIntegerField()),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order_item', models.ForeignKey(blank=True, help_text='Related order item if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.orderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='products.product')),
            ],
            options={
                'db_table': 'stock_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', '-created_at'], name='stock_trans_product_af2c54_idx'), models.Index(fields=['transaction_type'], name='stock_trans_transac_b2b788_idx')],
            },
        ),
    ]
