# Generated by Django 5.2.6 on 2025-12-02 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_orderitem_cancellation_note_and_more'),
        ('products', '0017_product_low_stock_threshold_stocktransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='Specific variant if transaction is variant-level', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to='products.productvariant'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['variant', '-created_at'], name='stock_trans_variant_98773d_idx'),
        ),
    ]
