# Generated by Django 5.2.6 on 2025-12-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_stocktransaction_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetailedimage',
            name='cloud_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='cloud_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariantimage',
            name='cloud_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
