# Generated by Django 5.2.6 on 2025-12-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_productdetailedimage_cloud_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporaryupload',
            name='file',
        ),
        migrations.AddField(
            model_name='temporaryupload',
            name='cloud_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temporaryupload',
            name='public_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
