# Generated by Django 5.2.6 on 2025-12-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_remove_temporaryupload_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetailedimage',
            name='public_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productimage',
            name='public_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productvariantimage',
            name='public_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
