# Generated by Django 5.2.6 on 2025-12-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_productdetailedimage_public_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetailedimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/detailed/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/'),
        ),
        migrations.AlterField(
            model_name='productvariantimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/variants/'),
        ),
    ]
